### ISSUE TITLE
Tomcat is not Running

### ISSUE THREAD

**Issue by baba-dude** [KAMI911/ansible-role-tomcat#1]
If we run the Playbook, it will run successfully but web page will not be displayed. 
If run the start up script manually in the catalina/bin/ startup.sh. Then the webpage will appear.

Is there anything we need to do in the playbook to fix this issue ??

**Comment by KAMI911** [comment]
There is an init.d script in /etc/init.d/{{ tomcat_process_name }} where process name is 'tomcat_app_sys'. If you use default you can start Tomcat via:
`/etc/init.d/tomcat_app_sys restart`
command. Currently it does not start the service automatically. However it is a good idea to add an variable and make (re)start optional. Is this what you want?

**Comment by baba-dude** [comment]
I tried the /etc/init.d/tomcat_app_sys restart runnig this commnad. Still it didn't work. If you can add it in the playbook itself, that would be much appreciated.
Thank you.

**Comment by baba-dude** [comment]
Thanks for the update. All the tasks are executed properly in the role. But not sure why it is not loading in the browser.
When can you add the feature in the playbook ?
Thank you so much for the reply.

**Comment by KAMI911** [comment]
Feature added. Thank you for the report!
